[build]
  # Vite构建命令
  command = "pnpm build"
  # 构建输出目录
  publish = "dist"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"

# SPA重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 可选：处理API路由
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Headers配置（可选，用于缓存优化）
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
